# Docker compose file for ${{PROJECT_NAME}}
version: '3.8'

services:
  # ${{PROJECT_NAME}} application server
  webserver:
    build: .
    container_name: '${{PROJECT_NAME}}-app'
    restart: 'always'
    ports:
      - "${{HOST_APP_PORT}}:80"
    depends_on: 
      - database
    volumes: 
      - ${{VOLUME_APACHE_HTML}}:/var/www/html
      - ${{VOLUME_APACHE_LOGS}}:/var/log/apache2
      - ${{VOLUME_APACHE_PHP_CONFIG}}:/usr/local/etc/php
    env_file:
      - environment.env

  # MySQL database
  database:
    image: mysql:${{MYSQL_VERSION}}
    container_name: '${{PROJECT_NAME}}-database'
    restart: 'always'
    ports:
      - "${{HOST_MYSQL_PORT}}:3306"
    volumes: 
      - ${{VOLUME_MYSQL_DATA}}:/var/lib/mysql
      - ${{VOLUME_MYSQL_LOGS}}:/var/log/mysql
    env_file:
      - environment.env

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${{PMA_VERSION}}
    container_name: '${{PROJECT_NAME}}-phpmyadmin'
    depends_on:
      - database
    env_file:
      - environment.env
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${{HOST_PMA_PORT}}:80'
    volumes: 
      - /sessions
      - ${{VOLUME_PMA_PHP_CONFIG}}:/usr/local/etc/php/conf.d