# Docker compose file for ${{PROJECT_NAME}}
version: '3.9'

services:
  # ${{PROJECT_NAME}} React frontend
  frontend:
    build: frontend
    container_name: ${{PROJECT_NAME_CONTAINER}}-frontend
    restart: always
    volumes:
      - ./frontend/src:/code/src
      - /project/node_modules
    networks:
      - react-spring
    ports:
      - 3000:3000
    depends_on:
      - backend

  # ${{PROJECT_NAME}} Spring backend
  backend:
    build: backend
    container_name: ${{PROJECT_NAME_CONTAINER}}-backend
    restart: always
    networks:
      - react-spring
      - spring-mysql
    env_file:
      - environment.env
    depends_on:
      - database

  # MySQL database
  database:
    image: mysql:${{MYSQL_VERSION}}
    container_name: ${{PROJECT_NAME_CONTAINER}}-db
    restart: always
    volumes:
      - ${{VOLUME_MYSQL_DATA}}:/var/lib/mysql
      - ${{VOLUME_MYSQL_LOGS}}:/var/log/mysql
    networks:
      - spring-mysql
    env_file:
      - environment.env

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${{PMA_VERSION}}
    container_name: ${{PROJECT_NAME_CONTAINER}}-phpmyadmin
    depends_on:
      - database
    env_file:
      - environment.env
    ports:
      - ${{HOST_PMA_PORT}}:80
    volumes:
      - /sessions