# Go CI

name: Go CI

on:
  push:
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            prepare_command: GO111MODULE=on go get github.com/urfave/cli/v2
            build_script: chmod +x build.sh; ./build.sh
          - os: windows-latest
            prepare_command: go env -w GO111MODULE=on && go get github.com/urfave/cli/v2
            build_script: .\build.bat

    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: ${{ matrix.prepare_command }}
    - name: Build testwise
      run: ${{ matrix.script_name }}